# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: 2.1.4
_src_path: gh:algorandfoundation/algokit-fullstack-template
author_email: noell.lpz@gmail.com
author_name: Norman Lopez
cloud_provider: netlify
contract_name: hello_world
preset_name: production
project_name: cultivest_contract

